### PR TITLE
Fix bad spec return values

### PR DESCRIPTION
**Pull request by peaceful-james**
Small PR for fixing bad specs (my fault!)

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Thinking more about it, it will be confusing for newcomers to understand why they have to manage these two return types. Especially cause the norm for `is_*?` functions in Elixir is to return a boolean.

What about:
- Renaming `is_burner_mx_record?` to `check_domain_mx_record`
- Take the logic for checking mx_record out of `is_burner?`. Either we add a new `check_burner` (with a consistent return type) or we let users call `is_burner_mx_record` by themselves

**Comment by peaceful-james** [comment]
> Thinking more about it, it will be confusing for newcomers to understand why they have to manage these two return types. Especially cause the norm for `is_*?` functions in Elixir is to return a boolean.
> 
> What about:
> 
> * Renaming `is_burner_mx_record?` to `check_domain_mx_record`
> * Take the logic for checking mx_record out of `is_burner?`. Either we add a new `check_burner` (with a consistent return type) or we let users call `is_burner_mx_record` by themselves

Yes, I actually expected this as the response to my original PR. I will make a new PR over the weekend. Thanks @Betree

**Comment by peaceful-james** [comment]
I have not forgotten about this. I will make a PR when I get some time.

**Comment by Betree** [comment]
No rush @peaceful-james, do it when you'll have the time. Thank you for these contributions!

**Comment by peaceful-james** [comment]
@Betree I made a PR, as promised: https://github.com/Betree/burnex/pull/52

Two tests are failing for me, on the master branch (JFYI).

**Comment by peaceful-james** [comment]
Closing in favour of https://github.com/Betree/burnex/pull/52

**Pull request closed without merging**
