### PR TITLE
Perf mapset

### PR DESCRIPTION
**Pull request by tomciopp**
Instead of iterating over the entire list of domains, use a MapSet to check if the domain we are looking for has been blocked. Instead of taking milliseconds, this operation will now take nanoseconds to perform. Use the update command to refresh the list of temporary email domains.

### CODE REVIEW

**Comment by tomciopp** [comment]
@Betree Any updates here?

**Review by Betree — COMMENTED** [review]
Hi @tomciopp, sorry for the delay on this. It looks like a really good change, thank you for opening this PR.

I think the only thing we're missing before merging is to update the typespec to `MapSet.t(binary())` in https://github.com/Betree/burnex/blob/51fa00c6f03eafab35435805157f7d679ba382f6/lib/burnex.ex#L59.

We'll introduce this as a breaking change, since people relying on `providers` may need to update their integrations.

**Comment by tomciopp** [comment]
@Betree Added a commit for the typespec change.

**Comment by Betree** [comment]
Perfect, thanks!

**Pull request merged**
